let UserName = prompt("Enter your name")
let UserSurname = prompt("Enter Your surnaem")
let UserAge = prompt("Enter Your age")
let UserAddres = prompt("Enter your addres")
let UserBirthday = prompt("Enter your Birthday")
let UserHight = prompt("Enter your hight")
let UserWight = prompt("Enter your wight")

console.log(UserName)
console.log(UserSurname)
console.log(UserAge)
console.log(UserAddres)
console.log(UserBirthday)
console.log(UserHight)
console.log(UserWight)